### ISSUE TITLE
number of output channels with wsclean_add_bands

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#117]
It seems factor computes the wrong channelsout ? (or maybe I am confused?)

-I have 23 blocks
-wsclean_nchannels_factor = 6
-wsclean_add_bands = True

The resulting channelsout is 3 ?

Should it not be 4?

23 + 1 / 6 = 4

**Comment by darafferty** [comment]
Yep, it was a bug.  Should be fixed now.

**Comment by rvweeren** [comment]
It is not fixed, still see the same error (channelsout is 3) on the master branch

**Comment by darafferty** [comment]
Oops, this was fixed only on the "tecsolve" branch. I've now fixed it on master as well.
