### ISSUE TITLE
checkfactor key shortcuts

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#15]
Could you also add keyboard shortcuts for the options below ?

INFO - factor:progress - Left-click on a facet to see its current state
INFO - factor:progress - Middle-click on a facet to display its image
INFO - factor:progress - Right-click on a facet to display its selfcal solutions and images

(to circumvent middle mouse button emulation problems over ssh/vnc)

**Comment by darafferty** [comment]
I have added the keyboard shortcuts:

INFO - factor:progress - Left-click on a direction to select it and see its current state
INFO - factor:progress - Right-click on a direction to deselect it
INFO - factor:progress - (In both cases, pan/zoom mode must be off)
INFO - factor:progress - Press "c" to display calibrator selfcal images for selected direction
INFO - factor:progress - Press "f" to display facet image for selected direction
INFO - factor:progress - Press "t" to display TEC solutions for selected direction
INFO - factor:progress - Press "g" to display Gain solutions for selected direction
INFO - factor:progress - Press "u" to update display (display is updated automatically every minute)

**Comment by rvweeren** [comment]
Excellent, I'll close this issue.

**Comment by rvweeren** [comment]
David, could you also add an open (maybe "p" ?) to open the "slow gain" phases ? (they are good to spot issues when the tec+sphase fails to converge, you then get the slow gain phases trying to compensate)

Reinout

**Comment by darafferty** [comment]
The slow phase plots should open together with the slow amplitude ones (with "g"). You can page through the plots with the space bar or, to jump to a specific plot, you can left click on the first plot (which will open the Image Magick menu), click File -> Select, and then choose the plot you want to see.

**Comment by rvweeren** [comment]
Ah, I see (I did not know about the space bar option). I'll close this.

**Comment by wndywllms** [comment]
Not a major bug, but for me 'f' puts the checkfactor plot into fullscreen mode, as well as opening the facet image, then 'f' takes it out of fullscreen mode and opens another facet image. Perhaps it is better not to use a keyboard shortcut that already does something else.

**Comment by darafferty** [comment]
Hmm. For me, "f" does nothing by default.

**Comment by darafferty** [comment]
OK, I've found a way to override the system defaults so that the Factor ones always take precedence. I'll commit the fix next week.

**Comment by rvweeren** [comment]
BTW I also have the same issue as Wendy with the "f" key.

**Comment by darafferty** [comment]
I've now updated checkfactor to override defaults that conflict with its shortcuts, so this problem should be fixed.

**Comment by rvweeren** [comment]
I still have the issue with the "f" key (updated factor yesterday so the fix does not seem to work) as reported by Wendy.

**Comment by mhardcastle** [comment]
I had the same problem yesterday, can't reproduce it now though running the same code. Perhaps there's some sort of race as to what catches the keystroke. But it would be better to avoid the standard keystrokes, anyway.

**Comment by darafferty** [comment]
OK, I've changed the "f" shortcut to "i" (which I don't think is a standard shortcut, but according to http://matplotlib.org/users/navigation_toolbar.html, neither is "f"), and I've also moved the shortcut override code to a different spot that hopefully will avoid the race condition.

**Comment by rvweeren** [comment]
Tested, worked.
