### ISSUE TITLE
 error: "Selected less than one frequency bands" in facetselfcal

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#179]
I have no idea why it crashes at the "subtract_high" step 72 of 85 (error remains with the Jan 2017 updates). Log attached.

2016-12-29 07:46:58 ERROR   facetselfcal_facet_patch_639: Selected less than one frequency bands.

[pipeline.log.gz](https://github.com/lofar-astron/factor/files/717249/pipeline.log.gz)

**Comment by darafferty** [comment]
I found the problem -- it was not handling the data properly for patch-type directions (i.e., those without an associated facet) for which multiscale clean is turned on. It should work now, but you need to roll back the statefile in the facetselfcal/facet_patch_639 directory to the "make_new_cal_skymodel" step before restarting.

**Comment by rvweeren** [comment]
Thanks, I updated and restarted the facetselfcal for that facet from the beginning , but now it even crashes earlier in the facetselfcal, at the "prepare_imaging_data (step 72 out of 82)". Log attached.

exit status 0: /bin/sh -c python /home/rvweeren/software/lofaroct2016/opt/LofIm2/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 21 127.0.1.1 45360
2017-01-20 08:46:14 DEBUG   facetselfcal_facet_patch_639.executable_args: compute.dispatch results job 21: job_duration: 3.23194313049, returncode: 0 
2017-01-20 08:46:14 DEBUG   facetselfcal_facet_patch_639.executable_args: 
2017-01-20 08:46:14 WARNING facetselfcal_facet_patch_639.executable_args: 
2017-01-20 08:46:14 INFO    facetselfcal_facet_patch_639.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /home/rvweeren/software/lofaroct2016/opt/LofIm2/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 18 127.0.1.1 45360
2017-01-20 08:46:14 DEBUG   facetselfcal_facet_patch_639.executable_args: compute.dispatch results job 18: job_duration: 3.3670630455, returncode: 0 
2017-01-20 08:46:14 DEBUG   facetselfcal_facet_patch_639.executable_args: 
2017-01-20 08:46:14 WARNING facetselfcal_facet_patch_639.executable_args: 
2017-01-20 08:46:14 INFO    facetselfcal_facet_patch_639.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /home/rvweeren/software/lofaroct2016/opt/LofIm2/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 19 127.0.1.1 45360
2017-01-20 08:46:14 DEBUG   facetselfcal_facet_patch_639.executable_args: compute.dispatch results job 19: job_duration: 3.3673479557, returncode: 0 
2017-01-20 08:46:15 DEBUG   facetselfcal_facet_patch_639.executable_args: Adding node_logging_information
2017-01-20 08:46:15 DEBUG   facetselfcal_facet_patch_639.executable_args: Writing data map file: /p3600/rvweeren/P214_52_full_preapply/results/facetselfcal/facet_patch_639/mapfiles/make_sourcedb_high.mapfile
2017-01-20 08:46:15 INFO    facetselfcal_facet_patch_639.executable_args: recipe executable_args completed
2017-01-20 08:46:15 INFO    facetselfcal_facet_patch_639: Beginning step expand_sourcedb_high
2017-01-20 08:46:15 INFO    facetselfcal_facet_patch_639: Beginning step prepare_imaging_data
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: *******************************************
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: Failed pipeline run: facet_patch_639
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: Detailed exception information:
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: <type 'exceptions.KeyError'>
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: 'select_imaging_bands'
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: *******************************************
2017-01-20 08:46:15 ERROR   facetselfcal_facet_patch_639: LOFAR Pipeline finished unsuccesfully.
2017-01-20 08:46:16 WARNING facetselfcal_facet_patch_639: recipe facetselfcal_facet_patch_639 completed with errors
[pipeline.log.gz](https://github.com/lofar-astron/factor/files/721231/pipeline.log.gz)

**Comment by darafferty** [comment]
This may be the problem I fixed with commit d9ac58e, some 5 or 6 hours after the first fix. Can you check that you have the changes from it as well?

**Comment by rvweeren** [comment]
I updated, now it progresses to step "mask6 (step 78 of 88)", and then crashes.

Looks to be related to the PyBDSM low-res masking. Log attached.
(I think the error is "2017-01-23 12:26:40 ERROR   node.lofar.python_plugin: Stokes value ?? is not contained in this StokesCoordinate")


[pipeline.log.gz](https://github.com/lofar-astron/factor/files/724454/pipeline.log.gz)

**Comment by darafferty** [comment]
Indeed, the error is occurring in the masking script (the message comes from pyrap), but I can't reproduce it on my own data. Can you send me the image (`/p3600/rvweeren/P214_52_full_preapply/results/facetselfcal/facet_patch_639/L343226_SBgr046-10_uv.dppp.pre-cal_chunk9.wsclean_image_full_low-MFS-image.fits`), the facet file (`/p3600/rvweeren/P214_52_full_preapply/state/facet_patch_639_save.pkl`) and the region file (`/data6/rvanweeren/P214+52scripts/s639.rgn`) so I can debug it?

**Comment by darafferty** [comment]
It turned out to be an issue with the way the script was trying to convert from RA, DEC to x, y. Should be fixed now (though I don't know why it did not show up before)

**Comment by rvweeren** [comment]
I updated but it still crashes at the masking step, same error it seems (log attached)

2017-01-25 12:43:55 WARNING facetselfcal_facet_patch_639.executable_args: Number of sources formed from Gaussians   : 0
2017-01-25 12:43:56 DEBUG   facetselfcal_facet_patch_639.executable_args: Results for job 0 submitted by ('127.0.0.1', 48335)
2017-01-25 12:43:56 ERROR   node.lofar.python_plugin: Stokes value ?? is not contained in this StokesCoordinate
2017-01-25 12:43:56 INFO    node.lofar.python_plugin: Total time 3.5081s; user time: 3.4111s; system time: 0.6019s
2017-01-25 12:43:56 DEBUG   node.lofar.python_plugin: Start time was 1485366232.9984s; end time was 1485366236.5067s
2017-01-25 12:43:57 DEBUG   facetselfcal_facet_patch_639.executable_args: 
2017-01-25 12:43:57 WARNING facetselfcal_facet_patch_639.executable_args: 
2017-01-25 12:43:57 INFO    facetselfcal_facet_patch_639.executable_args: Subprocess completed with exit status 1: /bin/sh -c python /home/rvweeren/software/lofaroct2016/opt/LofIm2/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py 0 127.0.1.1 35197
2017-01-25 12:43:57 ERROR   facetselfcal_facet_patch_639.executable_args: Remote process python /home/rvweeren/software/lofaroct2016/opt/LofIm2/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py ['/p3600/rvweeren/P214_52_full_preapply/results/facetselfcal/facet_patch_639/L343226_SBgr046-10_uv.dppp.pre-cal_chunk9.wsclean_image_full_low-MFS-image.fits', '/usr/local/lib/python2.7/dist-packages/FACTOR-1.0-py2.7.egg/factor/scripts/make_clean_mask.py', ['/p3600/rvweeren/P214_52_full_preapply/results/facetselfcal/facet_patch_639/L343226_SBgr046-10_uv.dppp.pre-cal_chunk9.wsclean_image_full_low-MFS-image.fits', '/p3600/rvweeren/P214_52_full_preapply/results/facetselfcal/facet_patch_639/L343226_SBgr046-10_uv.dppp.pre-cal_chunk9.wsclean_image_full_low-MFS-image.mask6'], {'threshpix': '20', 'adaptive_rmsbox': 'True', 'atrous_do': 'True', 'threshisl': '10', 'vertices_file': '/p3600/rvweeren/P214_52_full_preapply/state/facet_patch_639_save.pkl', 'region_file': '/data6/rvanweeren/P214+52scripts/s639.rgn', 'rmsbox': '(80,20)', 'exclude_cal_region': 'False', 'img_format': 'fits'}, '/p3600/rvweeren/P214_52_full_preapply/results/facetselfcal/facet_patch_639', False, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'gnu', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'SHLIB_PATH': '/home/rvweeren/software/root/lib:', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'LOFARDATAROOT': '/opt/lofar/data', 'OMP_NUM_THREADS': '8', 'PYTHONPATH': '/home/rvweeren/software/lofaroct2016/opt/LofIm2/lib/python2.7/site-packages:/home/rvweeren/software/root/lib:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/lib/python:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/lib:/home/rvweeren/software/wcsaxes/build/lib/python/:/home/rvweeren/software/pyvo/build/lib/python/:/home/rvweeren/software/wcsaxes/build/lib/python/:/home/rvweeren/software/pyvo/build/lib/python/:/home/rvweeren/software/wcsaxes/build/lib/python/:/home/rvweeren/software/pyvo/build/lib/python/::/home/rvweeren/scripts/pp:/home/rvweeren/scripts/pp:/home/rvweeren/scripts/pp', 'COMPIZ_BIN_PATH': '/usr/bin/', 'LIBPATH': '/home/rvweeren/software/root/lib:', 'DYLD_LIBRARY_PATH': '/home/rvweeren/software/root/lib:', 'LOFARROOT': '/home/rvweeren/software/lofaroct2016/opt/LofIm2', 'MANPATH': '/home/rvweeren/software/root/man:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/lib/jvm/java-8-oracle/man', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'PATH': '/home/rvweeren/software/lofaroct2016/opt/LofIm2/sbin:/home/rvweeren/software/lofaroct2016/opt/LofIm2/bin:/home/rvweeren/software/root/bin:/home/rvweeren/software/heasoft-6.16/x86_64-unknown-linux-gnu-libc2.19-0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/rvweeren/software/casapy/casa-release-4.5.2-el6:/home/rvweeren/software/wsclean-code/wsclean/build/:/home/rvweeren/software/ds9/:/home/rvweeren/software/UDR/src/:/home/rvweeren/software/losoto:/home/rvweeren/software/losoto/tools:/home/rvweeren/software/casapy/casa-release-4.5.2-el6:/home/rvweeren/software/wsclean-code/wsclean/build/:/home/rvweeren/software/ds9/:/home/rvweeren/software/UDR/src/:/home/rvweeren/software/losoto:/home/rvweeren/software/losoto/tools:/home/rvweeren/software/casapy/casa-release-4.5.2-el6:/home/rvweeren/software/wsclean-code/wsclean/build/:/home/rvweeren/software/ds9/:/home/rvweeren/software/UDR/src/:/home/rvweeren/software/losoto:/home/rvweeren/software/losoto/tools', 'LD_LIBRARY_PATH': '/home/rvweeren/software/lofaroct2016/opt/LofIm2/lib:6599LD_LIBRARY_PATH:/usr/local/lib'}] failed on localhost
2017-01-25 12:43:57 DEBUG   facetselfcal_facet_patch_639.executable_args: compute.dispatch results job 0: job_duration: 4.34146094322, returncode: 1 
2017-01-25 12:43:58 DEBUG   facetselfcal_facet_patch_639.executable_args: Adding node_logging_information
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639.executable_args: A job has failed with returncode 1 and error_tolerance is not set. Bailing out!
2017-01-25 12:43:58 WARNING facetselfcal_facet_patch_639.executable_args: Note: recipe outputs are not complete
2017-01-25 12:43:58 WARNING facetselfcal_facet_patch_639.executable_args: recipe executable_args completed with errors
2017-01-25 12:43:58 WARNING facetselfcal_facet_patch_639: make_clean_mask reports failure (using executable_args recipe)
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: *******************************************
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: Failed pipeline run: facet_patch_639
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: Detailed exception information:
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: make_clean_mask failed
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: *******************************************
2017-01-25 12:43:58 ERROR   facetselfcal_facet_patch_639: LOFAR Pipeline finished unsuccesfully.
2017-01-25 12:43:58 WARNING facetselfcal_facet_patch_639: recipe facetselfcal_facet_patch_639 completed with errors


[pipeline.log.gz](https://github.com/lofar-astron/factor/files/730622/pipeline.log.gz)

**Comment by darafferty** [comment]
Darn it -- I missed a couple more places where the problem occurs. Try it now.

**Comment by rvweeren** [comment]
Ok, just updated, I think make_clean_mask.py works now, at least it does not crash at this stage anymore....let's what happens next.

**Comment by rvweeren** [comment]
Ok, arrived at step 82 of 88 successfully, seems we can close this ticket.
